//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektiTietokanta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektiYlläpitoEntities2 : DbContext
    {
        public ProjektiYlläpitoEntities2()
            : base("name=ProjektiYlläpitoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Projektit3> Projektit3 { get; set; }
        public virtual DbSet<Henkilot3> Henkilot3 { get; set; }
        public virtual DbSet<Tunnit3> Tunnit3 { get; set; }
    }
}
